#Dependabot will check the dependencies in this repo for updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"


  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      # Check for updates to on nuget packages every weekday
      interval: "weekly"
